server:
  port: 8020
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    instance :
#    是否把当前服务IP注册到eureka服务端
      prefer-ip-address : true