server:
  port: 8050
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    instance :
#    是否把当前服务IP注册到eureka服务端
      prefer-ip-address : true
feign:
  hystrix:
    enabled: true